"Tools":
  "Adopt":
    Postgres:
      purpose: "Primary Data Store"
      why_summary: "ACID-compliant, highly flexible, scalable and performant.  Advanced features for data modeling and querying"
    Resque:
      purpose: "Background Jobs"
      more_details_url: https://github.com/resque/resque/tree/1-x-stable
  "Trial":
    JHipster:
      purpose: "Indexed Search"
      more_details_summary: "Application generator used to develop quickly a modern web application using AngularJS and the Spring Framework."
      more_details_url: https://jhipster.github.io/
      why_summary: "Used by platform team with great success."
  "Hold":
    JIRA:
      purpose: "Issue & Task Management"
      more_details_url: https://www.atlassian.com/software/jira/
      why_summary: "Abandoned for lighterweight solutions"
"Platforms":
  "Adopt":
    Heroku:
      purpose: "Infrastructure"
      more_details_url:
    S3:
      purpose: "Remote file system"
      more_details_url: https://aws.amazon.com/s3/
  "Trial":
    iOS:
      purpose: "Mobile Application Development"
      more_details_url: https://en.wikipedia.org/wiki/IOS
      why_summary: "Only used for client-facing mobile app"
  "Assess":
    AWS:
      purpose: "Infrastructure"
      more_details_url: https://aws.amazon.com
      why_summary: "Hosts the VPN"
  "Hold":
"Techniques":
  "Adopt":
    "Weekly sync-ups with Business Partners":
      purpose: "Roadmap Planning"
      more_details_summary: |+
        As we have no formal product management (by design), each engineering team has a weekly meeting with their relevant _business partners_, who are the stakeholders for that part of the businsess.
        For example, the MOPS team meets with the VP of Warehouse Operations and their reports.

        The format of the meeting differs by team, but generally, it's a time to review the status of ongoing work, adjust the priority of anything, and discuss any issues of the day.
        Teams typicaly employ a “Rolling Agenda” which is a shared Google Doc that anyone can edit.
        Anyone can place an item on the Agenda, and it is up to them to lead the discussion and collect next-steps, if any.

        Typically, the first meeting of the month will be a deeper-dive into the team's roadmap and to generally set priorities for the month.
    "Pull Requests":
      purpose: "Code Review & Change Management"
      more_details_url: http://multithreaded.stitchfix.com/blog/2013/07/30/our-git-workflow/
  "Trial":
    "HTTP Services":
      purpose: "Application Integration"
      why_summary: "Probably ready to adopt.  Some older code still using gems & messages-as-APIs"

  "Assess":
    "Consumer-driven tests for services":
      purpose: "Ensure changes to services do not break upstream clients"
      more_details_url: http://martinfowler.com/articles/consumerDrivenContracts.html
      why_summary: "Ops experimenting (see Pact)"
  "Hold":
    "Shared Gems":
      purpose: "Application Integration"
      why_summary: "Difficult to manage, doesn't scale"
"Languages and Frameworks":
  "Adopt":
    Ruby:
      purpose: Middleware Programming
      more_details_url: https://www.ruby-lang.org/en/
  "Trial":
    CoffeeScript:
      purpose: Browser Programming
      more_details_url:
      why_summary: "Most apps are using this, with Admin being a notable exception"

  "Assess":
    Go:
      more_details_url: https://golang.org/
      purpose: "Middleware Programming"
      why_summary: "Currently experimenting"
  "Hold":
    "Objective-C":
      purpose: "iOS Development"
      more_details_url: https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html
      why_summary: "We have seen much lower error rates in production using Swift than the devs have seen with similar apps written in Objective-C"
